### ISSUE TITLE
Add box.json to support ForgeBox

### ISSUE THREAD

**Issue by seancorfield** [framework-one/fw1#260]

**Comment by seancorfield** [comment]
Dropping this from 3.0 since I'm not up to speed on what CommandBox / ForgeBox is capable of these days.

**Comment by bdw429s** [comment]
Here's some notes from Slack that Sean asked me to paste in here:


You can install a package without box.json (unlike NPM that requires it) but the CLI gets grumpy and bugs you.  Basically, I default the version and treat it like a basic package that installs in the root in a folder named after the slug.  

As far as adding a box.json to FW/1, there are a couple options:
You can build a zip (that you'll need to host somewhere) that only has the contents of the "framework" folder and set the `packageDirectory` property equal to `framework`

Or you can point tot he GitHub repo, ignore everything but the "framework" folder and set `createPackageDirectory` to false.  It takes a bit of dancing if the name of the folder matters, since CommandBox installs packages in a folder named after their slug by default.  This option will only install the "framework" folder but will dump it in the web root so it doesn't end up being /fw1/framework which would require the dev to move it.

Here are the docs on box.json:
http://ortus.gitbooks.io/commandbox-documentation/content/packages/boxjson/boxjson.html

See the "installation" section (5.6.4) for details on ignores ( follows .gitIgnore ) as well as the packageDirectory properties.

Also, here are some more docs on creating packages.
http://ortus.gitbooks.io/commandbox-documentation/content/packages/creating_packages/creating_packages.html

**Comment by seancorfield** [comment]
Tagging @cfchef who said he might be interested in looking into this. Thanks!

**Comment by seancorfield** [comment]
Closed by #357
