### ISSUE TITLE
DI/1 clean up and deduction issues

### ISSUE THREAD

**Issue by seancorfield** [framework-one/fw1#283]
Address issues found during documentation rewrite for 3.0.

**Comment by seancorfield** [comment]
Note: assuming `./controllers` and `./model` doesn't seem to work for subsystems on Windows, per Martin Baur's thread.

**Comment by seancorfield** [comment]
Blocking issue for 3.0: the default behavior for DI/1 with subsystems doesn't seem to work on all platforms per Martin Baur's issue.

**Comment by seancorfield** [comment]
The latest change committed above should address paths that start with `.` so I'm asserting this fixed and closing it.

**Comment by seancorfield** [comment]
Reopened based on feedback from Nathan Strutz. Still causes problems on Windows:

This change left me with this error:
`The ..controllers.myController name is not a valid component or interface name.`
`discoverBeansInFolder()` function came with `mapping="./controllers"`, then the returned value from `deduceDottedPath()` is
```
CFCPATH  ./controllers
DOTTED   ..controllers
EXPPATH  C:/inetpub/wwwroot/app/controllers
MAPPED   ./controllers
```
Reverting this change fixed it for me, but of course does not fix #283. I'm not sure what your strategy here is, but as an outsider, I can see a brute-force fix to add `dotted = reReplace(dotted, "^\.+", "");` after line 338 to correct it.

**Comment by seancorfield** [comment]
So it looks like the code still doesn't handle leading dots correctly.

**Comment by jcberquist** [comment]
I took a look at this. I don't have a handle on what is going on here, but I might have at least a partial answer, at least as regards subsystems. When `setupFrameworkDefaults()` is called, it ensures that `variables.framework.base` has a trailing `/`. See lines 2075-9:
```
if ( !structKeyExists(variables.framework, 'base') ) {
    variables.framework.base = getDirectoryFromPath( variables.cgiScriptName );
} else if ( right( variables.framework.base, 1 ) != '/' ) {
    variables.framework.base = variables.framework.base & '/';
}
```
And then in the `setupSubsytemWrapper()` on line 2379:
```
subLocations = listAppend( subLocations, variables.framework.base & "/" & subsystem & "/" & relLoc );
```
This means that sub location paths are going to have `//` in them, either at the start of the path if `variables.framework.base` is just `/` or somewhere in the middle of the path. I ran some quick tests and the extra `/` doesn't seem to bother `expandPath()`, hence directory listings will run just fine and  DI/1 will find the cfcs, but it will obviously cause the `deduceDottedPath()` function to insert an extra `.` in cfc paths because it does a replace for every instance of `/` in the path.

**Comment by seancorfield** [comment]
Nice bit of detective work @jcberquist - I'll go through and clean that up tomorrow because there may be other places where it isn't consistent. I don't think that's the only problem tho' since the problems people are reporting happen only on Windows (although it's possible this ripples through and causes the problem only on that platform!). I'm setting up a Windows test environment to ensure that I can repro platform-specific stuff like this.

**Comment by seancorfield** [comment]
I think this is finally fixed now. I've tested on Windows and Mac and addressed the issue above.
