### ISSUE TITLE
setupTraceRender() is not called if renderData() has been called in the request

### ISSUE THREAD

**Issue by jcberquist** [framework-one/fw1#301]
As per the google groups thread, it would be nice to have `setupTraceRender()` called even when `renderData()` is used. My use case would be rendering trace data to the console when using `renderData()`, but I would prefer to let `frameworkTraceRender()` continue to output for HTML requests. Thus, perhaps, `renderData()` could be called with an argument indicating whether `renderData()` was being used, so that `setupTraceRender()` would not have to look at `request._fw1` to see if the `renderData` key exists there (it seems like that would leaving the public API and delving into the internals of FW1).

**Comment by seancorfield** [comment]
My suggestion:

* add optional `string output = "html"` argument to `setupTraceRender()`
* change logic in `frameworkTraceRender()` to omit test on rendering data (in first `if` only)
* change call to `setupTraceRender()` in `frameworkTraceRender()` to pass either `"html"` or `"data"` depending on whether we are rendering data
* update any/all documentation for tracing to reflect new functionality

This maintains backward compatibility for anyone who has not overridden either trace function.

For folks who have overridden these functions, it may break apps that use `renderData()` if their overridden versions still output HTML to the regular stream (since that was suppressed previously) but they can easily fix this by making their `setupTraceRender()` behavior conditional on the new argument.

The documentation should reflect that possibility and explain the workaround.

**Comment by seancorfield** [comment]
Fixed by PR #302.
