### ISSUE TITLE
Can we make framework reloads thread-safe?

### ISSUE THREAD

**Issue by atuttle** [framework-one/fw1#311]
This is something that I recent-ish-ly refactored in for Taffy.

Use case:
- I want to have `reloadOnEveryRequest` enabled in my dev environment
- I have some pages that initiate many AJAX requests to the framework for data at page load
- It is possible, and increasingly likely with more AJAX requests, that the reload from one request will cause an error in another request, because services/controllers/etc are being rebuilt and cached, and the cache is purged during that process.

It is also possible that an attacker could use knowledge of your reload key + password to harass your website (/visitors) by constantly flooding you with reload requests.

The way that I approached it for Taffy was [to rewrite the (re)initialization methods to return data instead of modifying application scope directly](https://github.com/atuttle/Taffy/issues/168), and inject it all into application scope at once, after everything has been built and cached. It was no small undertaking, but in the end I feel Taffy is much better for having it.

If it's something you'd be willing to consider, I would be happy to work on it and submit a pull request. I may ask for some guidance here and there.

**Comment by seancorfield** [comment]
It's certainly something I'd like the framework to do in a thread-safe way but it's been low on my priority list because I never use `reloadApplicationOnEveryRequest` because I think it's a poor workflow (and, besides, for us most of our Model is Clojure and we reload that code differently to how we reload the CFML code).

**Comment by jochemd** [comment]
We were having an issue where every browser using an application would do one AJAX requests every second. Reloading the application through the URL took about 3 seconds so there was about a 50% error rate in that with one visitor. If we enabled reloading on every request requests with errors would appear within seconds.

I modified the framework to use the variables scope where possible, and only use the application scope as a cache and make sure to be consistent there. We have not done correctness tests with artificial test cases, but now we can keep it running with reloading on every request enabled for minutes with multiple users without seeing errors.

See https://github.com/jochemd/fw1/commit/0d8f8cedc7379d3d6103b1f1f6d1ed64cf404792 for our changes against the develop branch.

This is intended to solicit feedback on the approach taken, not necessarily for immediate integration. Issues I see with the code is the overhead of a function call instead of a map key lookup. But since it doesn't crash anymore, for our use case the overhead is well worth it (and can potentially be reduced by switching some places to a hardcoded variables scope.

**Comment by seancorfield** [comment]
Looks like a nice simplification there @jochemd -- I saw it turned up as part of your PR for #337 -- and it removes the lock which is nice. I suspect the minor overhead is worth it, overall, since it also trades out a dynamic, variable-based lookup in most cases.

**Comment by seancorfield** [comment]
Solved by #337 which includes @jochemd 's fix.

**Comment by atuttle** [comment]
:+1:
