### ISSUE TITLE
diConfig not propagated to subsystems

### ISSUE THREAD

**Issue by Ronner** [framework-one/fw1#314]
When using subsystems, the diConfig configuration property is not propagated to subsystems.

For instance;

```cfc
variables.framework = {
	usingSubsystems = true,
	diConfig = {
		initMethod = 'postconstruct',
		omitDirectoryAliases = true
	}
};
```

postconstruct is never called on subsytems.

**Comment by seancorfield** [comment]
Yes, this is a known limitation since the main config may well be inappropriate for subsystems. I'll have to give it some thought. Tentatively marking as a 3.1 consideration.

**Comment by Ronner** [comment]
In my opinion I guess the convention should be that subsystems get the same main diConfig, in order to keep configuration to a minimum, and have the ability to override the diConfig for subsystems through the variables.framework.subsystems structure.

**Comment by seancorfield** [comment]
Fixed in 3.1 develop branch.

**Comment by jcberquist** [comment]
I was looking at the latest develop version given the changes today, and this commit caused issues for me because now the di1 load listener is being called when the subsystem bean factories are created (as well as when the default bean factory is) and the load listener attempts to add an alias for a bean which doesn't exist in any subsystem bean factory. I can "fix" this by adding subsystem diConfig structs or by calling `getBeanInfo()` in the load listener to verify the bean is there, which is fine (and quite possibly the correct way I should have been doing things); I just thought I would mention it.

**Comment by seancorfield** [comment]
Yup, that's actually intentional. There are a number of subtleties around combining subsystems and bean factories where the basic defaults _work out of the box_ but as soon as you start to customize, you need to consider both the main bean factory _and_ the subsystem bean factories.

I would recommend adding subsystem `diConfig` structs for now but I'm open to suggestions (in another ticket -- or on the [Gitter channel](https://gitter.im/framework-one/fw1)) for ways to make subsystems and bean factories play nicer together -- since I do not use subsystems.
