### ISSUE TITLE
FW1 3.0 Error Handler Being Interrupted By Framework Error on CF 9.0.1

### ISSUE THREAD

**Issue by sneiland** [framework-one/fw1#319]
On CF 9.0.1 when a undefined variable error is being thrown in a controller function the error handler is being interrupted by an error in the framework itself.

"Invalid to call the layout method at this point."

This problem only appears on CF 9.0.1

![image 2015-04-18 at 10 13 31 am](https://cloud.githubusercontent.com/assets/632619/7233095/3f9c7624-e74d-11e4-90dd-cfa1feb6a0ca.png)

![image 2015-04-18 at 10 15 06 am](https://cloud.githubusercontent.com/assets/632619/7233106/4e0194c4-e74d-11e4-80a5-6c1d3009f54b.png)

**Comment by seancorfield** [comment]
I strongly suspect this is related to #317. 

You say this only happens on ACF9.0.1? So the exact same code reports the undefined variable correctly on Railo/Lucee/ACF10+?

That's curious...

**Comment by sneiland** [comment]
Yes, runs fine on 9.0.2 but fails on 9.0.1.

**Comment by seancorfield** [comment]
OK, then it's a different issue.

Looking at the flow in the code, I don't see how it could fail on 9.0.1 but work on other versions unless this is a bug in 9.0.1 around nested struct handling.

I don't have 9.0.1 available to test but if you can figure out why it can go through `onRequest()` without setting `request._fw1.controllerExecutionComplete` (the flag tested in `internalLayout()`), I'd entertain a PR on `develop` to fix this.

Otherwise, at this point, I'd be tempted to just change the lowest supported version from `9.0.1` to `9.0.2` and "blame Adobe" for the problem :)

**Comment by sneiland** [comment]
We discussed at and we decided to roll back to 2.5 for now until we upgrade cf

**Comment by seancorfield** [comment]
So 2.5 runs just fine and reports the error as expected? Curioser and curioser. I'm _almost_ tempted to create a VM and install 9.0.1 just to debug it... :)

**Comment by seancorfield** [comment]
After giving this some thought, I was leaning toward just dropping support for 9.0.1 in FW/1 3.0 (since 9.0.1 is five years old and 9.0 is six years old) but then I did some digging and found that while 9.0.2 is technically a free upgrade from 9.0 and 9.0.1, it was not made available as an updater -- you would have to uninstall 9.0 / 9.0.1 and install 9.0.2 instead (due to the removal of Verity).

So at this point I'm going to leave it as an edge case bug on an old version of ColdFusion and simply not fix it myself -- since it doesn't affect _normal_ operation, just bug reporting at startup. Anyone who wants to dig into the problem on 9.0.1 and submit a PR is welcome to do so.

**Comment by seancorfield** [comment]
As of FW/1 3.1 I have dropped official support for ColdFusion 9.0.1 so I'm going to close this. Either move to 9.0.2 (or later, or another engine), or stay on an earlier FW/1 version. Sorry.
