### ISSUE TITLE
Routes enhancement

### ISSUE THREAD

**Issue by guillaume-boivin** [framework-one/fw1#325]
Hi,

a typical use case of routes is product/:id-:name.html. Currently that is not possible (ex : product/2-super-computer.html, :id = 2-super-computer).

To be able to use this route we would need to add a way to specify what will be matched by a specific placeholder variable.

For that example we would need to be able to specify that :id must only match numeric values and that name may match anything.

Is it a feature that  you would be interested in adding ? 

If so I could propose a way of doing it and possibly PR it afterwards.

**Comment by seancorfield** [comment]
Well, with `-` as a legal character in placeholder names, that wouldn't be possible anyway right now.

Since you could have `/product/:id_name.html` and easily split the `:id_name` value in your handler into an ID as `listFirst(rc.id_name,'-')` and the name as `listRest(rc.id_name,'-')` I'm not very inclined to add this sort of thing to the core routes. After all, what works for your specific use case might not work for _everyone_ and that's the difference between core functionality and per-application functionality.

Leaving this open for a while for additional discussion however.

**Comment by guillaume-boivin** [comment]
I get your point. 

But from a SEO perspective (wich is a bit why we want routes in the first place) not being able to do this is really not that great as the best SEO word separator is a hyphen.

Your solution would work but feels like a hack, I would personnaly try to modify the framework core code to not burden my controller code with the same hack over and over again before using this solution.

**Comment by seancorfield** [comment]
And the SEO separator *would* be a hyphen. Read what I wrote more carefully.

**Comment by seancorfield** [comment]
Hint: `rc.id_name` would be `2-super-computer`.

**Comment by guillaume-boivin** [comment]
yeah I get that, but it still a hack or workaround if you prefer, not a feature.

**Comment by guillaume-boivin** [comment]
Having said that, thanks for the workaround thought (and the quick reply), I haven't tough about it. For the enhancement I'm requesting, guess it's a niche case from your standing point, I'm ok with that.

**Comment by seancorfield** [comment]
Just to be clear, I'm saying that `/product/:id_and_name.html` should map to something like `/product/view/productid/:id_and_name` -- so `/product/2-super-computer.html` becomes an invocation of `view()` in `controllers/product.cfc` and it has `id_and_name` in `rc`, so you can split out your product ID and your product name in the controller.

That's where I believe such logic should go -- otherwise the declarative nature of routes starts to need all sorts of complexities to deal with data types and validation and parsing and so on.

Also, consider `:id-:name` in the first place (assuming `-` was not considered part of `id`!). Why should `2-super-computer` bind as `id=2&name=super-computer` rather than `id=2-super&name=computer` which is what would happen with greedy matching in regex.

**Comment by guillaume-boivin** [comment]
If you could state that :id can only be matched by [0-9]+ it would work I think . More generally state that a placeholder variable uses a custom regex to match. But you resumed it well by saying that it would "need all sorts of complexities to deal with data types". It's clearly gonna complete things as it get's more flexible.

What I'm requesting is a way to say :id-:name.html is this regex ([0-9]+)-([a-zA-Z0-9-]+)\.html

**Comment by seancorfield** [comment]
Yeah, I can see what you're asking for. Remember that the enhancement would have to play well with resource templates/resource packs as well (which, essentially, auto-generate resource regexes based on certain patterns).

The choices for enhancing routes to handle this would include:

* extending the in-place syntax to allow for placeholders to optionally include some sort of (limited?) regex or data types -- and consider how that would impact regex-based parsing of the placeholder (which we just went through in another ticket)
* adding an optional way to annotate the routes with data types or regexes for each placeholder in the string -- and then expanding all the route processing to additionally run more regexes or pattern matching as each placeholder is extracted from the URI

I don't like the added complexity implications of either of those (personally I think the current routes functionality is already too complex with resource templates/packs!).

**Comment by jcberquist** [comment]
Not to derail this issue, but (briefly)... I agree Sean regarding the resource template packs (which you let me add to FW1). Looking at it now, I think it is too specific and constraining; it would make more sense, and be more consistent with the principles of FW1, to leave that sort of route generation to an overridden `getRoutes()` method. I wonder how widespread the usage of it is?

**Comment by guillaume-boivin** [comment]
"I wonder how widespread the usage of it is?"

I'm already using getRoutes() to dynamically set my routes based on a xml config file that the seo dudes are going to edit (via a console built-in the site and accessible on the dev tier).

"leave that sort of route generation to an overridden getRoutes() method"

For this feature to work, I would need to override processRouteMatch() (and possibly other stuff too).

**Comment by guillaume-boivin** [comment]
The more I look at it, the more I think that what I want is a custom placeholder variable matcher/replacer (aka a placeholder variable interpolator). A class with a place holder interpolator interface that clients could implement and modify to there taste, with a default implementation that would be the one we have now. But I would be destroying the "it fits in one file" philosophy of fw/1.

**Comment by seancorfield** [comment]
If you identify the _functions_ that would need to be extracted (so you could override them in your `Application.cfc`), then I'd entertain something in that direction. Functions, not classes. OOP is overkill for a lot of things :)

**Comment by guillaume-boivin** [comment]
Added a syntax for placeholder specific regex : 9543b78552dbd27a526083ac72a3846bd86eeb90

{placeholder:regex}, so we could have product/{id:[0-9]+}-:name.html that targets product.detail?id={id:[0-9]+}&name=:name. 

- You need to repeat the placeholder with the regex in the target route too (could be changed).
- You can't put } in your placeholder specific regex.

**Comment by seancorfield** [comment]
That looks pretty good @guillaume-boivin !

I definitely think we wouldn't want to repeat the regex in the target route so `{id:[0-9]+}` in the route would match `:id` in the target so if you can add that in, I'd be happy to accept a PR against the `develop` branch.

Not worried about the `}` in the regex restriction.

Thanks for making sure to add a test too.

I'm planning to cut RC 2 soon so if you can get the PR ready this weekend, it'll make RC 2, otherwise it'll have to go into 3.5.

**Comment by seancorfield** [comment]
Implemented in #349
