### ISSUE TITLE
Lower case requirement for folders/filenames?

### ISSUE THREAD

**Issue by cfsimplicity** [framework-one/fw1#326]
The docs ( http://framework-one.github.io/documentation/developing-applications.html ) say that controller, layout and view folders/filenames "must be all lowercase", but I am using mixed case for many of these with no apparent problems (on Windows).

**Comment by dnando** [comment]
Julian,

There is only an issue on LInux, where the file system is case sensitive. I
asked Sean to implement a switch for this to optionally turn the
lowercasing feature off, and he implemented it, but he strongly recommends
against it. His argument is that users can type urls, and then the
developer has no control whether the casing they use correctly matches that
on the (Linux) file system.

In your case, the argument against would be that you may run into some
trouble porting your app to Linux.

ioftenwindupwithlongfilenamesinmyviews, and the all lower case issue is
only somewhat of a pain that I live with. Maybe hy-phens would be better
than camelCasing. An argument for hyphens might be that Google can parse
the url into a key-word-phrase.



Aria Media Sagl
Via Rompada 40
6987 Caslano
Switzerland

+41 (0)91 600 9601
+41 (0)76 303 4477 cell
skype: ariamedia

**Comment by cfsimplicity** [comment]
Hi Nando, I understand what you say, but I was really just pointing out an apparent factual inaccuracy in the docs. They say you "must" use lowercase, which isn't true if you're on Windows. Maybe just needs a note to that effect.

**Comment by shawnoden** [comment]
A note to the Windows case would probably be good. I don't like definitive words like "must", because there will "always" be an exception that questions the validity of the statement. But being cognizant of case-sensitivity probably wouldn't be a bad idea, especially for devs who don't typically use case-sensitive systems. One of the things that used to drive me absolutely batty was seeing application.cfm in a directory. Sure it works. But only until it doesn't. And do you know how hard that is to troubleshoot if you don't know that your hardware team migrated your app to a Linux host? _IF_ you even see an error. :-)

**Comment by seancorfield** [comment]
Feel free to send a PR here https://github.com/framework-one/framework-one.github.io (which is where documentation issues should be raised anyway).

**Comment by seancorfield** [comment]
BTW, if you use DI/1 to manage all your controllers and services/beans, the lowercase restriction goes away even on Linux because lookup for access is done via CFML structs which remove the case sensitivity issues!

**Comment by cfsimplicity** [comment]
Sorry, Sean, didn't twig that there was a separate repo for the docs. PR submitted there.
