### ISSUE TITLE
possible race condition in DI1 when using the init method of beans 

### ISSUE THREAD

**Issue by jcberquist** [framework-one/fw1#329]
I make use of the feature of DI1 that lets you return something other than the created bean via the init method, where that replaces the original bean in DI1. Occasionally I have encountered the situation where if two threads request such a bean at the same time, and it has not yet been cached (I notice this happening on/immediately after a FW1 reload), it is possible for the first request to create the un-inited bean and then before it calls the init method on it, the second request gets back the un-inited bean (since it is already in the beanCache but has not yet been replaced). 

While I have noticed this because I expect the original bean to be replaced with a new bean, it seems to me this could be an issue wherever the init() method is used, even when not returning something other than the original bean.

**Comment by seancorfield** [comment]
Looks like the only way to make that completely safe would be to wrap the whole body of `resolveBeanCreate()` in an exclusive named lock, based on the bean name...

**Comment by seancorfield** [comment]
@jcberquist I pushed a commit that shows markers around the block of code that would need to be locked. There's a few issues:

* Right now, the only code with a lock is the bean discovery which is quick
* The `resolveBeanCreate()` block involves resolving other code so it's a lot of code to lock around.
* That code includes a recursive call which makes it very tricky to lock (since it would have to be isolated to a separate function and an additional lock-or-not-lock argument being passed thru).

It's a lot of work for an edge case...

...so here's a suggestion that might also work for you: since this is all about singletons and initialization, consider putting a call to `.load()` in a load listener. That's the approach we've taken at World Singles: we declare a load listener for all our customizations and the very last line is `di1.load()` -- where `di1` is the argument to the load listener function.

If that solves your problem, then I'd be inclined to just close this without action. Our problem was mainly due to lazy initialization of singletons so it may not be sufficient to solve your issue. Please let me know.

**Comment by jcberquist** [comment]
@seancorfield, thanks for the suggestion. 

At first I thought using `load()` might not be sufficient because even as `load()` is calling `getBean()` for every bean in `beanInfo`, other requests are not blocked from calling `getBean()` for one of the referenced beans that gets replaced via its `init()`. So the race condition would still be present, since there would still be a time where the original un-inited bean was in the bean cache. 

But then I realized that since I use DI1 with FW1, and FW1 will trigger the load listener when it adds itself to DI1, which happens before `setBeanFactory()` is called and DI1 is cached in the application scope, there shouldn't be a situation where another thread has access to the same instance of DI1 and the load listener has not been called and completed. Does that seem right to you?

In any case, I do agree that this is an edge case which would take a lot of effort to solve (the locking would be a pain), and I am happy to have you close it. I think using `.load()` should work, but I could probably also use DI1's `factoryBean()` for these beans, so either way, I can avoid the problem.

**Comment by seancorfield** [comment]
Yeah, `.load()` happens before you get the factory back so, even if it all gets run multiple times on a reload, you should get back one complete, consistent set of beans. In theory :)

Reloading an app under heavy load is always a little dangerous - although with the changes coming in 3.1 it should be safer.
