### ISSUE TITLE
reload with generateSES=true fails

### ISSUE THREAD

**Issue by adeleusiere** [framework-one/fw1#358]
function isFrameworkReloadRequest relies on URL scope only, so when generateSES is set to true, the application is not reloaded as expected for /index.cfm/main/default/reload/true for example

**Comment by seancorfield** [comment]
Use `/index.cfm/main/default?reload=true` instead. This is intentional.

**Comment by adeleusiere** [comment]
It is really confusing for developers, in my opinion. To understand why the following:
<a href="#buildURL('?reload=true')#">Reload</a>
is not reloading the application when you click on it (with SES true), is not so evident.
But anyway, thanks for the feedback.

**Comment by seancorfield** [comment]
You're the first person that's been confused by it in six years :)

You can use: `<a href="#buildURL('')#?reload=true">Reload</a>` -- but since the `framework.reload` value is intended to be a _secret_, like a password, I'd strongly recommend not using the default value and not hardcoding it in your views anyway...

**Comment by adeleusiere** [comment]
eheh, I like to be first :)
Absolutely agree with this explanation. Closed.
When developing is convenient to put a quick "reload" button, I've felt into this pit without noticed the change of behavior when I've activated the SES...
