### ISSUE TITLE
Transients not properly autowired on subsequent get

### ISSUE THREAD

**Issue by seancorfield** [framework-one/fw1#420]
See https://github.com/aliaspooryorik/fw1/commit/3a038bc6b5e028364f428d8e88e792b7db9ad89e

@aliaspooryorik says "I think what happens is that when you call getBean on subsequent requests for a transient, it's wiring up the object using the info from variables.accumulatorCache, but doesn't return that instance (or something like that)"

**Comment by georgebridgeman** [comment]
From what I have found, the issue is caused by the setters being called on `injection.bean` but in the case of transients, that reference never updated after it has been instantiated the first time. The first instance is then held in `variables.accumulatorCache['myTransient'].injection['myTransient']`, and the setters are called on that instance on subsequent calls, but a different instance is returned.

I fixed the issue by putting this code in `resolveBeanCreate`, just below `accumulator.bean = bean`; on line 894:
```
if(!isSingleton(beanName) && structKeyExists(accumulator.injection, beanName)) {
	accumulator.injection[beanName].bean = accumulator.bean;
}
```
I'm not convinced that this is the correct fix though - smells very hacky - so haven't submitted a PR. I didn't have this issue with previous releases either, so I think the problem is caused elsewhere and my fix merely masks the issue.

**Comment by seancorfield** [comment]
Thanks @georgebridgeman -- that's actually very helpful. The reason this bug has appeared is the caching code added to try to avoid walking dependencies multiple times for transients by not forcing regeneration of the accumulator data, but this seems to be a path through where the newly generated transient needs to be overridden in the cache (although there's still a possibility of multiple transients generated in a single recursive resolution phase where only one of them would have setters called properly... that may be enough of an edge case not to worry about).
