### ISSUE TITLE
Reusing ColdBox modules: could FW/1 read/load ModuleConfig.cfc?

### ISSUE THREAD

**Issue by seancorfield** [framework-one/fw1#486]
This arose out of the discussion around @cfchef integrating @elpete's QB ColdBox module and what FW/1 could do to make that integration easier.

**Comment by jmohler1970** [comment]
I like how it is does SQL queries in a more CFML manner.

**Comment by mjclemente** [comment]
I'm definitely intrigued at the possibility. The Box team is doing some great stuff, and the number of modules on Forgebox is growing, with an understandable tendency towards the ColdBox ecosystem. It would be awesome to be able to plug more of them into FW/1 apps.

**Comment by elpete** [comment]
One thing that would be useful for me as a ColdBox module author are patterns I can put in my modules to make them easier to tie in to FW/1, even if it is just a cursory understanding that I can slap in the documentation.  Things like how to wire up dependencies in DI/1 or patterns like using a `diEngine` service instead of `wirebox` directly (though that may be solved with the WireBox adapter for DI/1).

**Comment by seancorfield** [comment]
As explained on the mailing list, this just isn't practical in the general case. I'm probably going to leave the two supporting functions (`moduleMappings()` and `installModules()`, and the new `nullObject` CFC) in the code base but not document them so folks who want to work with ColdBox modules have something to start from. I'll be happy to review PRs that expand this functionality in the future -- if folks with deeper knowledge of ColdBox want to push this further.
