### ISSUE TITLE
Make DI/1 aware that beans might be ORM entities

### ISSUE THREAD

**Issue by cybersonic** [framework-one/fw1#488]
I am just leaving this here so I can see if I can also use DI/1 to load (and inject) any services or transients into ORM based entities.

**Comment by cybersonic** [comment]
This would be a setting that you can add your ORM entities and when you do a `bf.getBean('User')` if it is a persisted entity it would always call `EntityNew('User')` but could also inject any non-persisted properties to the object (such as services)

**Comment by seancorfield** [comment]
The current way to handle that would be to extend `ioc.cfc` and override `construct()` and have it decide whether to call `createObject()` or `entityNew()` based on the dotted path of the CFC. Or it could load metadata and decide based on that. Would that be sufficient? I'd rather not have annotations in DI/1.

**Comment by cybersonic** [comment]
Yeah, I don't think we need to do anything with annotations, it would be checking the `persistent` attribute of the component metadata:
```
component  persistent="true" {}
```

I am pretty sure it already has the metadata loaded anyway right?

**Comment by seancorfield** [comment]
DI/1 loads and cleans up the metadata for each discovered bean but it does not pay attention to `persistent` other than to trigger implicit setters (i.e., property-based injection). So the metadata processing would need to track `persistent` and the various places that call `construct()` would need to check that metadata and decide what to do. Since `construct()` is a documented extension point, changing its signature would need to be handled with care -- users could already be overriding it and calling `entityNew()` instead of `createObject()` based on analysis of the `dottedPath` argument.

**Comment by lramirez925** [comment]
Sorry to ask this here and it may not be the same thing but while this works for new objects is there a best way for loaded objects as well?

**Comment by cybersonic** [comment]
@seancorfield Makes sense. If this is a way to do it I shall close this ticket. Maybe keep this tickett open so I can add an example extension point and add it to the code base and documentation? (if there isn't one already?)

**Comment by seancorfield** [comment]
@lramirez925 No idea what you're asking -- but whatever it is, it's a question for the mailing list, not here.

@cybersonic We'll leave this open. Core DI/1 code needs to change to accommodate this and I think we have a good path forward, based on this discussion. I've never used the built-in ORM because, well, you know my opinion of ORMs in general (and the built-in one in particular!), so I hadn't bothered to think through all the issues: I figured someone who cared enough about ORM would push that forward for me -- so thank you!

**Comment by seancorfield** [comment]
I think what I'll do here is add a new config setting, `constructEntities`, that determines how DI/1 should deal with persistent beans. It'll have three states: `new` -- use `new`/`createObject` (current behavior), `throw` -- throw an exception if asked to construct a persistent bean, `entity` -- treat persistent beans as entities (use `entityNew`). I'll default it to `throw` so that folks will not get a silent change of behavior and will be notified of a likely bug in their existing code.

**Comment by cybersonic** [comment]
That makes a lot of sense and it is a whole bang for buck kinda thing. I am just adding this as a aide memoire, that we should check what happens if there is an entityLoadListener (I am sure it will just work anyway) 

Thanks for your feedback!

**Comment by seancorfield** [comment]
lramirez@slack raised the very good point that having DI/1 handle `entityNew` but not autowiring properties for `entityLoad` would undercut the value of this.

**Comment by seancorfield** [comment]
It might be a good time to expand the functionality of `injectProperties()` to actually be useful by allowing it to accept an instance or array of instances and perform general property injection based on the type (I'd be inclined to require the bean name be specified as the second argument so that DI/1 knows what bean info / metadata to use without having to try to inspect the actual instance passed in!). This could then we used to do setter and property injection for entities created via `entityLoad()`.

It might also be the preferred way to handle ORM beans altogether: require users to create them via `entityNew()` or `entityLoad()` and then call `beanFactory.injectProperties( instanceOrArray, beanName )`?

**Comment by cybersonic** [comment]
I think both could work, but yeah `beanFactory.injectProperties( instanceOrArray, beanName )` is nearly exactly how I do it in some internal projects I have (Mongolator which populates a bean with MongoDB data)

**Comment by seancorfield** [comment]
Further discussion on the mailing list has effectively killed this idea, as far as I'm concerned:
* The entity name and the DI/1 bean name will not necessarily match so using `entityNew("beanName")` could well be the incorrect choice anyway.
* As an adjunct to that, `injectProperty( entityLoad( "entityName", pk ), "beanName" )` is ugly and feels hackish -- and looks very redundant if the entity name and bean name _do_ match.
* In the array case, @cameroncf noted that "the execution time spent injecting a bunch of stuff into the beans when the beans might not actually use anything that's injected is kinda expensive compared to the benefit."
