### ISSUE TITLE
FW1 and CF2021

### ISSUE THREAD

**Issue by ramparvataneni** [framework-one/fw1#527]
Anyone tried CF2021 with FW/1, please share your experience. We are receiving errors with CF2021.

Our FW/1 version is too old (2.1), however before upgrading to latest FW1 version, we would like to know if anyone tried CF2021.
The same application works fine with CF10.

We already tried upgrading to FW 3.0, but receiving same error.

The element at position 2 cannot be found.

TagContext	
array
1	
struct
COLUMN	0
ID	??
LINE	779
RAW_TRACE	at cfone2ecfc1133534638$funcONREQUEST.runFunction(D:\Development7\framework\one.cfc:779)
TEMPLATE	D:\Development7\framework\one.cfc
TYPE	CFML
Type	Expression
aDimension	-1
aIndex	2
Detail	An exception occurred while invoking an event handler method from Application.cfc. The method name is: onRequest.
Message	Event handler exception.
RootCause	
struct
Detail	[empty string]
ErrNumber	0
Message	The element at position 2 cannot be found.

**Comment by tonyjunkes** [comment]
We're gonna need some more details about your code, where/when/how you encounter the error, and framework settings (in Application.cfc) to be of any help.

I've done some general testing with the latest version of FW/1 on CF2021 and everything has worked as expected; including all of its unit tests. Using anything below the latest is going to be prone to issue by nature since the older versions do not get much long term support outside of the occasional security risk.

Regarding upgrading from version 2.1...

My initial suggestion would be to gradually introduce FW/1 version bumps and make changes as necessary based on anything that was a breaking change in that version until you are up to date with the latest version. Jumping from 2.1 to 3+ can be daunting due to a handful of breaking changes introduced along the way. I would review the links below for possible hints to code changes you are missing in order to progress.

- Version 2.2 introduced RESTful support via renderData() so I do not believe there was anything earthshattering.
- Version 2.5 introduced some deprecating changes, so it may be worth giving this a read: http://framework-one.github.io/blog/2014/05/26/fw1-2-5-is-released/.
- Version 3.0 introduced major changes going forward including the removal of deprecated features, so this is worth reading and reviewing your code base: http://framework-one.github.io/blog/2014/07/21/fw1-3-0-alpha-1-available-for-testing/
- Version 3.5 was a big push forward feature-wise including subsystems 2.0 among other things. It could be worth a read but it can all be found in the official docs. http://framework-one.github.io/blog/2015/10/21/fw1-3-5-0-released/

Hope this helps. Cheers.

**Comment by ramparvataneni** [comment]
Thanks for the response and suggestion. We will try to follow the steps listed.
